[build-system]
requires = ["setuptools", "Cython"]
build-backend = "setuptools.build_meta"

[project]
name = "pydisort"
version = "0.1"

[tool.setuptools]
ext-modules = [
  {name="pydisort", sources=["src/pydisort.pyx", "src/locate.c", "src/cdisort.c"]}
]
